version: '3'

services:
  pgedge-node-0:
    hostname: pgedge0
    image: test/pgedge
    environment:
      - NODE=pgedge0
    ports:
      - '15432:5432'
    volumes:
      - 'pgedge0:/data'

  pgedge-node-1:
    hostname: pgedge1
    image: test/pgedge
    environment:
      - NODE=pgedge1
    ports:
      - '25432:5432'
    volumes:
      - 'pgedge1:/data'

volumes:
  pgedge0:
    driver: local
  pgedge1:
    driver: local
